baseurl = "https://ysonsc.github.io"
title = "Dumpling Factory"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "ysonC"
  info = "Professional Dumpling Wrapper"
  description = "Yson's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.png"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2025

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/ysonC/"

# [[params.social]]
#   name = "Gitlab"
#   icon = "fa-brands fa-gitlab fa-2x"
#   weight = 2
#   url = "https://gitlab.com/johndoe/"
# [[params.social]]
#   name = "Twitter"
#   icon = "fa-brands fa-x-twitter fa-2x"
#   weight = 3
#   url = "https://twitter.com/johndoe/"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
